"""Concatenate agent/custom/*.py into a single main.py for Kaggle submission.

Strategy: inline modules in dependency order. Remove local `from .` imports.
Replace class-in-class references (all in same namespace after concat).
"""
import re
import os

MODULE_ORDER = [
    "board",
    "pathing",
    "plan",
    "tasks",
    "assigner",
    "executor",
    "spy",
    "economy",
    "agent",
]

def read(path):
    with open(path) as f:
        return f.read()


def strip_local_imports(src):
    """Remove `from .<module> import ...` (single or multi-line paren form)."""
    out = []
    lines = src.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        # Detect start of a local import
        if re.match(r"^\s*from \.\w", line) or re.match(r"^\s*from \.\s+import", line):
            # If line contains an open paren but no close paren, skip until close
            if "(" in line and ")" not in line:
                while i < len(lines) and ")" not in lines[i]:
                    i += 1
                i += 1  # skip the close-paren line too
                continue
            i += 1
            continue
        out.append(line)
        i += 1
    return "\n".join(out)


def main():
    parts = ["# Kaggriculture custom bot — Session 55 (v10)",
             "# Auto-generated by scripts/build_main.py",
             "# 5/5/6 herd, skip_se, 3-quad layout",
             ""]

    for mod in MODULE_ORDER:
        path = f"agent/custom/{mod}.py"
        src = read(path)
        src = strip_local_imports(src)
        parts.append(f"# --------- {mod}.py ---------")
        parts.append(src)
        parts.append("")

    # The Kaggle loader picks the last callable named `agent` (or last-defined
    # callable). Our `agent` function is already defined in agent.py's inline.
    # No extra glue needed.

    out = "\n".join(parts)
    with open("main.py.candidate", "w") as f:
        f.write(out)
    print(f"Wrote main.py.candidate  ({len(out)} bytes)")


if __name__ == "__main__":
    main()
